"""chat session update table

Revision ID: 4d37f5efc4a5
Revises: 4aa735b8b780
Create Date: 2025-06-29 23:39:24.616314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d37f5efc4a5'
down_revision: Union[str, Sequence[str], None] = '4aa735b8b780'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('chat_logs_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_chat_sessions_session_id'), table_name='chat_sessions')
    op.create_foreign_key(None, 'chat_sessions', 'chat_logs', ['chat_logs_id'], ['id'])
    op.drop_column('chat_sessions', 'session_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.create_index(op.f('ix_chat_sessions_session_id'), 'chat_sessions', ['session_id'], unique=True)
    op.drop_column('chat_sessions', 'chat_logs_id')
    # ### end Alembic commands ###
