"""update chatlog table

Revision ID: 8161aeb0d0f1
Revises: 
Create Date: 2025-06-27 13:24:43.755646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8161aeb0d0f1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_logs', sa.Column('messages', sa.JSON(), nullable=True))
    op.drop_index(op.f('ix_chat_logs_prompt'), table_name='chat_logs')
    op.drop_index(op.f('ix_chat_logs_response'), table_name='chat_logs')
    op.drop_column('chat_logs', 'prompt')
    op.drop_column('chat_logs', 'response')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_logs', sa.Column('response', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('chat_logs', sa.Column('prompt', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_chat_logs_response'), 'chat_logs', ['response'], unique=False)
    op.create_index(op.f('ix_chat_logs_prompt'), 'chat_logs', ['prompt'], unique=False)
    op.drop_column('chat_logs', 'messages')
    # ### end Alembic commands ###
