"""update chat session

Revision ID: 8f50fee93f39
Revises: 4d37f5efc4a5
Create Date: 2025-06-29 23:58:08.771156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f50fee93f39'
down_revision: Union[str, Sequence[str], None] = '4d37f5efc4a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # FIXED: Changed sa.String() to sa.Integer() to match chat_sessions.id
    op.add_column('chat_logs', sa.Column('session_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chat_logs', 'chat_sessions', ['session_id'], ['id'])
    op.drop_constraint(op.f('chat_sessions_chat_logs_id_fkey'), 'chat_sessions', type_='foreignkey')
    op.drop_column('chat_sessions', 'chat_logs_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('chat_logs_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('chat_sessions_chat_logs_id_fkey'), 'chat_sessions', 'chat_logs', ['chat_logs_id'], ['id'])
    op.drop_constraint(None, 'chat_logs', type_='foreignkey')
    op.drop_column('chat_logs', 'session_id')
    # ### end Alembic commands ###